### ISSUE TITLE
Cannot get program to run

### ISSUE THREAD

**Issue by rewilson75** [beiko-lab/MEGASAT#2]
Hello....We are just starting to transfer our microsatellite projects over to NGS and were planning on using this program to genotype our samples.  We have a couple of ongoing projects were we add to the datasets every year so we are transferring our legacy loci over to our MiSeq.  I was trying to test out the program using the test data on our computers to make sure I can get it to work but have been unable to do so far.  I am using the primer-input txt and the ErrorRate_FASTQ.gz_files as my data set folder.  

I am using a Windows 10 with 64-bit OS and have also tried the program on an Mac but got the same results.  I followed the instructions in the manual on how to install...just decompressed the zip folder.  

This is a screenshot of the GUI window.  Once I hit Run the program, immediately another window appears saying the program is complete but there is nothing written in the output directory.  I had a colleague try to run it on his windows machine but he got an error saying he needed the Pearl: ParallelForkManager installed.

![megasat](https://user-images.githubusercontent.com/22458805/45574466-9ac50b80-b81c-11e8-83e8-5beb289d8049.JPG)

If you have any ideas on what I am doing wrong or if there is something else I need installed on my computer that would be greatly appreciated.

thanks
Rob

**Comment by LuyaoZhan** [comment]
Hello Rob,

If you use the GUI on Windows, you don't need to install Perl. If the
program didn't show any error but no output was generated, probably is
because of the primer-input txt file. Could you send me your primer-input
file? Maybe it is because the forward and reverse primers are in the wrong
position in the text file. So MEGASAT cannot identify the loci in the NGS
data.

Best wishes
Luyao

**Comment by rewilson75** [comment]
Hi Luyao

Thank you for the quick reply.  Attached is the primer input file I used.  I originally tried it on some of my own data but when that didn't work, I tried the test data in this repository just to make sure I could get it to work.   I did notice in the other issue posted that the 5Flank and 3Flank need to be switched from what is in the manual.

[primer-input.txt](https://github.com/beiko-lab/MEGASAT/files/2384963/primer-input.txt)

Thank you
Rob

**Comment by LuyaoZhan** [comment]
I see. You are using the test data to test if you can run the program on
your computer. Have you decompress the fastq file in the
ErrorRate_FASTQ.gz_files?

Best wishes
Luyao

**Comment by rewilson75** [comment]
Hi Luyao

I have tried with the fastq files zipped and when that didn't work, I unzipped the files and put it in its own folder.  I didn't know if having compressed and decompressed in the same folder would cause issues.   I still got the same results where it said it ran within a second but no outfiles written. 

Best
Rob

**Comment by LuyaoZhan** [comment]
Hi Rob,

I think you can try to decompress all the fastq files in that
ErrorRate_FASTQ.gz_files folder. And then you can create a new folder and
put all the files (with suffix ".fastq") in that new folder. Then in the
GUI, put the directory of new folder as the data set folder. I remember
before I uploaded the program to the Github link, I have tested the program
couple of times on the test data. So it should be working if you can put
all the decompressed fastq files in the data set folder.

Best wishes
Luyao

**Comment by LuyaoZhan** [comment]
<img width="632" alt="screen shot 2018-09-14 at 3 40 28 pm" src="https://user-images.githubusercontent.com/12203125/45578173-b76d3d80-b834-11e8-8d0c-ea28f094f8e7.png">
Something like this.

**Comment by rewilson75** [comment]
Hi Luyao,

Sorry I had a typo in my previous comment.  After I tried with the zipped files, I unzipped the fastq.gz (75 of them) files and moved them into their own folder.  So it looks like what you have in my data folder.  When I run the program through the GUI using the primer-input file, I still do not get any errors or any output.  

![capture](https://user-images.githubusercontent.com/22458805/45578229-a9b3ba00-b82c-11e8-882f-53a814ed1bf6.JPG)

Best Rob

**Comment by LuyaoZhan** [comment]
Hi Rob,

I am testing on my laptop now. It looks like it is working. But mine is Macintosh OS. On MAC and Linux, it should install a Perl Module called Parallel::ForkManager. Right now I don't have access to Windows OS. When I get back to work next Monday, I can test the program on Windows to see what the problem is. I apologize for any inconvenience. 

Best wishes
Luyao

**Comment by rbeiko** [comment]
Hi Catherine,

Thanks for following up so quickly on this!

Btw I heard from the company last week and gave my reference :)

Best wishes
Rob

**Comment by LuyaoZhan** [comment]
Morning Rob,

Thank you again for the reference. There is no doubt that your reference helps me to get the offer so quickly. I got the official offer and will start working tomorrow. 

Best wishes
Catherine

**Comment by rewilson75** [comment]
Hi Luyao,

I am trying to see if I can get access to a MAC and have the Perl Module called Parallel::ForkManager installed as I am still not having any luck with my windows machine.

I do have general question regarding the program.  One of our legacy microsats has two repeats....GT followed by AT (sequence is below).  Can this type of microsatellite be run through MEGASAT where it will score both repeats as a single repeat length?

GGATCCCCCTGGAGCACGGTCAGTGCTTCCTTTGGGCTCGAGGTGTTTCCCCCAACCTAATTTACCATTG
AGTATTGCTGGATTTAATTGATTTGCTTTTTACCCCCAGTGTTCTGCTTTAAATAA**GTGTGTGTGTGTGT
GTGTGTGT**_ATATATATATATATATATATATATATATAT_TCTAATTCTTTCATATACTTAGTATTTGAGCT
GGAAATAATATAGCAGATTCTGGTATAGCAATGTG

Best
Rob

**Comment by LuyaoZhan** [comment]
Hi Rob,

Sorry for the late response. Today was my first day at work. So I was setting up my PC and other stuff all day. Actually for Windows, you don't need to install any Perl Module or Perl in your system since we compiled the Perl script into an executable. My PC at work only have Linux system. So I haven't tested the program for Windows. Hopefully I can get the Windows OS installed tomorrow. For MAC and Linux system, I have tested the program today and it worked. You just need to make sure you have successfully installed Parallel::ForkManager if you wanna run the program on Mac or Linux.  

For your question, in that special case, MEGASAT cannot score both repeats. If you put GT as the repeat in the primer.txt file, it will identify the longest GT repeats (allowing mismatches). Unfortunately, MEGASAT 1.0 cannot score two different repeats. 

Best wishes
Luyao

**Comment by LuyaoZhan** [comment]
Hi Rob,

This morning I tested the MEGASAT for Windows. It worked on my PC. And I don't have Perl installed. Have you decompressed the zipped file "Windows_1.0 for Windows". When I tried to run MEGASAT on  Windows this morning, I forgot to decompress the file. And it showed no error but no output was generated. So I think the reason probably is because you didn't decompress the file. 

Please let me know if that fix your issue. 

Best wishes
Luyao

**Comment by rewilson75** [comment]
Hi Luyao,

I have decompressed the file.  
Just so we are on the same page.  This is exactly what I did.
1. Downloaded the entire repository.
2. Unzipped MEGASAT-master folder
3. Unzipped MEGASAT_1.0 for Windows
4. Unzipped fastq.gz files and put unzipped files in thier own folder
5. Opened MEGASAT_GUI and opened the included pimer-input.txt file and the folder with the unzipped fastq files and selected output directory.  Set parameters.
6. Hit Run program

As soon as I hit Run program another window pops up and says the program is finished.  But there is no output.

I found access to a MAC and have installed the Perl Parallel:ForkManager and R on the computer.  I checked that R was installed properly by typing R in the terminal window and got version information.  I was able to get the Main GUI (Genotype.pl) to work for the test data as well as some on my own data.  When I tried to run the R GUI to create the plots, I ran into the same issue where it says it finished immediately but no output is created.  I was able to get the Mplot.R to work through the command line.  Since it works on your computer, it must be something how our work computers are setup. It might be that I will have to use the command line to run some of the functions.

Thanks again for taking the time to help me figure this out. I really appreciate it.

Best
Rob
